### ISSUE TITLE
Add badge to existing lists

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#253] opened 2015-07-30 16:16 UTC
Could use some help with getting the badge [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome) into existing lists. Comment on which you've done.

https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge

**Comment by jyguyomarch** [comment] 2015-07-30 16:21
You add this completely at the top of the README?

**Comment by jyguyomarch** [comment] 2015-07-30 16:24
Simply like that? https://github.com/jyguyomarch/awesome-productivity/tree/jyguyomarch-awesome-badge

**Comment by sindresorhus** [comment] 2015-07-30 16:29
Almost, should be right to the title. [Example](https://github.com/sindresorhus/awesome-nodejs).

**Comment by jyguyomarch** [comment] 2015-07-30 17:28
:+1:

**Comment by appleboy** [comment] 2015-07-31 01:04
:+1:

**Comment by aleksandar-todorovic** [comment] 2015-07-31 18:25
I have added it to the every list I'm managing: 

* https://github.com/aleksandar-todorovic/awesome-linux/commit/47778a7efc1839ed2b347a3747807e81e7dfeab0
* https://github.com/aleksandar-todorovic/awesome-c/commit/efb776ae1f053e2375e330cfe88cd793796c8f64
* https://github.com/aleksandar-todorovic/awesome-blogs/commit/0c356a61e01d64cc0e3215a2ce466b2380668277
* https://github.com/mehcode/awesome-atom/commit/a287e4dd7c0604fa76d731da43413f910f02146c

**Comment by AllThingsSmitty** [comment] 2015-08-01 15:30
I've added the badge to [Must-Watch CSS](https://github.com/AllThingsSmitty/must-watch-css). Prior I had included this blurb at the top of the list which I think is still valid:

> For other great lists check out [@sindresorhus](https://github.com/sindresorhus/)'s curated list of [awesome lists](https://github.com/sindresorhus/awesome/).

**Comment by n1trux** [comment] 2015-08-02 09:40
added to n1trux/awesome-sysadmin.

**Comment by Kickball** [comment] 2015-08-02 23:11
Added to [awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted).

**Comment by bolshchikov** [comment] 2015-08-04 14:56
Added to js-must-watch with PR of @AllThingsSmitty

**Comment by AllThingsSmitty** [comment] 2015-08-04 22:03
Could we simply list repo owners in a comment for this issue to notify them about using the badge? I know there are dozens but I'd be willing to do a little leg work.

**Comment by sindresorhus** [comment] 2015-08-04 22:04
@AllThingsSmitty Yes, that's a great idea :+1: :)

**Comment by AllThingsSmitty** [comment] 2015-08-04 23:20
@dypsilon, @JStumpp, @weblancaster, @busterc, @jondot, @benoitjadinon:

You're receiving this because you have repos listed in @sindresorhus's Awesome repo under the "Platforms" section. We're trying to apply branding to each report listed therein. Please see the initial comment on this issue for steps on adding the "Awesome" badge to your repo.

Thanks for your help.

**Comment by AllThingsSmitty** [comment] 2015-08-04 23:28
@sorrycc, @matteocrippa, @vinta, @kud1ing, @krispo, @passy, @avelino, @lauris, @markets
@planetruby, @razum2um, @h4cc, @isRuslan, @drobakowski, @svaksha, @LewisJEllis, @aleksandar-todorovic, @fear, @qinwf, @zhaopuming, @hachiojipm, @kdabir, @yissachar, @akullpp, @rizo, @seancoyne, @rabbiabram, @quozd, @ziadoz, @Fr0st-Brutal, @mat0thew, @ahkscript, @veelenga, @dzharii:

You're receiving this because you have repos listed in @sindresorhus's Awesome repo under the "Programming Languages" section. We're trying to apply branding to each report listed therein. Please see the initial comment on this issue for steps on adding the "Awesome" badge to your repo. Please respond with which repos you've updated with the badge.

Thanks for your help.

**Comment by AllThingsSmitty** [comment] 2015-08-04 23:34
@addyosmani, @davidsonfellipe, @lvwzhen, @enaqx, @mateusortiz, @Granze, @gianarb, @instanceofpro, @diegocard, @willianjusten, @dnbard, @peterkokot, @NoahBuscher, @nmec, @wasabeef, @cjwirth, @davidtheclark, @Urigo, @turobson, @fonsopacifer, @deanhume, @brunopulis, @sachin1092, @sota0805, @wbkd:

You're receiving this because you have repos listed in @sindresorhus's Awesome repo under the "Front-End Development" section. We're trying to apply branding to each repor listed therein. Please see the initial comment on this issue for steps on adding the "Awesome" badge to your repo. Please respond with which repos you've updated with the badge.

Thanks for your help.

**Comment by AllThingsSmitty** [comment] 2015-08-04 23:37
@rosarior, @humiaozuzu, @veggiemonk, @iJackUA, @ITCase, @PerfectCarl, @friendsofcake, @EmanueleMinotto, @chiraggude, @ekremkaraca, @sergeyklay, @phanan, @fcambus, @stve:

You're receiving this because you have repos listed in @sindresorhus's Awesome repo under the "Back-End Development" section. We're trying to apply branding to each repo listed therein. Please see the initial comment on this issue for steps on adding the "Awesome" badge to your repo. Please respond with which repos you've updated with the badge.

Thanks for your help.

**Comment by AllThingsSmitty** [comment] 2015-08-04 23:38
I've sent the note above to the repo owners listed under Platforms, Programming Languages, Front-End Dev, and Back-End Dev. I'll try to get to some more tomorrow.

**Comment by davidsonfellipe** [comment] 2015-08-04 23:40
@AllThingsSmitty Thanks, added on https://github.com/davidsonfellipe/awesome-wpo/

**Comment by willianjusten** [comment] 2015-08-04 23:41
Added on https://github.com/willianjusten/awesome-svg =)

**Comment by yissachar** [comment] 2015-08-05 00:13
Added to https://github.com/yissachar/awesome-dart

**Comment by peterkokot** [comment] 2015-08-05 00:20
Added to https://github.com/peterkokot/awesome-dojo

**Comment by seancoyne** [comment] 2015-08-05 00:30
Added to https://github.com/seancoyne/awesome-coldfusion

**Comment by LewisJEllis** [comment] 2015-08-05 01:08
Added to https://github.com/LewisJEllis/awesome-lua

**Comment by sindresorhus** [comment] 2015-08-05 01:20
Some additional ones that weren't higlighted: @sturobson @afonsopacifer @sotayamashita

**Comment by sindresorhus** [comment] 2015-08-05 01:20
Thanks @AllThingsSmitty :)

**Comment by davidtheclark** [comment] 2015-08-05 01:23
Added to https://github.com/davidtheclark/scalable-css-reading-list

**Comment by dzharii** [comment] 2015-08-05 02:10
#### @sindresorhus @AllThingsSmitty 

#### OMG guys, that was so annoying.  :rage4: 
#### I have a backlink to your list, but I am not going to include that badge. 

![image](https://cloud.githubusercontent.com/assets/36020/9076771/826878fe-3adb-11e5-900a-4b62b671a5c8.png)

**Comment by mateusortiz** [comment] 2015-08-05 02:14
Added on https://github.com/mateusortiz/webcomponents-the-right-way
thanks @AllThingsSmitty

**Comment by aleksandar-todorovic** [comment] 2015-08-05 02:16
@dzharii Sure it's annoying (it was annoying to me too before I had unsubscripted from this thread), but what else could be done? It's painstaking to create 100+ issues on 100+ different repositories.

**Comment by sindresorhus** [comment] 2015-08-05 02:21
@dzharii Then unsubscribe to the thread. This is unfortunately the best to reach everyone. For most it will just result in one notification if you use the web UI.

**Comment by phanan** [comment] 2015-08-05 03:07
Added to https://github.com/phanan/htaccess.

**Comment by svaksha** [comment] 2015-08-05 03:13
On Tue, Aug 4, 2015 at 11:29 PM, Matt Smith <notifications@github.com> wrote:
>
> @planetruby, @razum2um, @h4cc, @isRuslan, @drobakowski, @svaksha, @LewisJEllis, @aleksandar-todorovic, @fear,
> You're receiving this because you have repos listed in @sindresorhus's Awesome repo under the "Programming Languages"

Added to http://svaksha.github.io/Julia.jl

SVAKSHA ॥  http://about.me/svaksha  ॥

**Comment by phanan** [comment] 2015-08-05 03:28
@svaksha Shouldn't it be right to the right (no puns) of the title?

**Comment by lvwzhen** [comment] 2015-08-05 03:44
Added on https://github.com/lvwzhen/tools
thanks @AllThingsSmitty

**Comment by sotayamashita** [comment] 2015-08-05 04:24
Added to https://github.com/sotayamashita/awesome-css .

**Comment by humiaozuzu** [comment] 2015-08-05 04:43
Added to https://github.com/humiaozuzu/awesome-flask/commit/0bce3279dfdb072ac0a78d02a8441541af747e98

**Comment by sachin1092** [comment] 2015-08-05 04:56
Added to https://github.com/sachin1092/awesome-material

**Comment by svaksha** [comment] 2015-08-05 05:07
On Wed, Aug 5, 2015 at 3:29 AM, Phan An <notifications@github.com> wrote:
>
> @svaksha Shouldn't it be right to the right (no puns) of the title?

I dont think so. Each repo is the star with useful information
regarding a specific topic and it should stay that way, not clutter or
deflect attention to unrelated content - Ideally a badge or link to
external resources should be at the bottom or elsewhere pointing
people to additional resources that may be useful to them and yet
somewhat related to the main content that people came looking for.
SVAKSHA ॥  http://about.me/svaksha  ॥

**Comment by instanceofpro** [comment] 2015-08-05 05:10
Added to https://github.com/instanceofpro/awesome-backbone and https://github.com/instanceofpro/awesome-marionette

**Comment by iJackUA** [comment] 2015-08-05 06:43
Added to https://github.com/iJackUA/awesome-vagrant

**Comment by quozd** [comment] 2015-08-05 06:52
Added to https://github.com/quozd/awesome-dotnet :) Nice badge btw

**Comment by sergeyklay** [comment] 2015-08-05 06:57
:+1:

**Comment by veggiemonk** [comment] 2015-08-05 07:17
Done for https://github.com/veggiemonk/awesome-docker
:cool:

**Comment by gianarb** [comment] 2015-08-05 07:22
Done https://github.com/gianarb/awesome-angularjs/blob/master/README.md

**Comment by JStumpp** [comment] 2015-08-05 07:31
Done for https://github.com/JStumpp/awesome-android/ in https://github.com/JStumpp/awesome-android/commit/b2b339a58af4132b361e747a4ce80f5df24b4880

**Comment by Granze** [comment] 2015-08-05 08:11
Awesome **Polymer** here: https://github.com/Granze/awesome-polymer done

**Comment by nmec** [comment] 2015-08-05 08:12
[Awesome Ember](https://github.com/nmec/awesome-ember) checking in.

**Comment by EmanueleMinotto** [comment] 2015-08-05 08:18
Badge added: https://github.com/EmanueleMinotto/awesome-symfony2/commit/849d43c91e1c6e91aa32cd0a422c5d148372f93d

**Comment by deanhume** [comment] 2015-08-05 08:37
Added to https://github.com/deanhume/typography

**Comment by veelenga** [comment] 2015-08-05 09:08
Added to https://github.com/veelenga/awesome-crystal
BTW, nice badge

**Comment by akullpp** [comment] 2015-08-05 10:49
https://github.com/akullpp/awesome-java https://github.com/akullpp/awesome-java/pull/197

Replaces the "inspired by" line.

**Comment by matteocrippa** [comment] 2015-08-05 10:56
Awesome swift should be fine now ( https://github.com/matteocrippa/awesome-swift )

**Comment by brunopulis** [comment] 2015-08-05 13:13
Added on https://github.com/brunopulis/awesome-a11y/ :+1:

**Comment by afonsopacifer** [comment] 2015-08-05 13:13
Added to https://github.com/afonsopacifer/awesome-flexbox
:)

**Comment by dypsilon** [comment] 2015-08-05 17:42
@AllThingsSmitty thanks for the ping.

[frontend-dev-bookmarks](https://github.com/dypsilon/frontend-dev-bookmarks) are badged.

**Comment by AllThingsSmitty** [comment] 2015-08-05 19:45
@prakhar1989, @okulbilisim, @josephmisiti, @edobashira, @theimpossibleastronaut, @MaciejCzyzewski, @jbhuang0604, @ChristosChristofidis, @kjw0612, @onurakpolat, @caesar0301, @youngwookim, @igorbarinov, @papers-we-love, @JanVanRyswyck, @tayllan, @enjalot/, @owainlewis, @marcobiedermann, @vhf, @ligurio, @dariubs, @hackerkid:

You're receiving this because you have repos listed in @sindresorhus's Awesome repo. We're trying to apply branding to each repo listed therein. Please see the initial comment on this issue for steps on adding the "Awesome" badge to your repo. Please respond with which repos you've updated with the badge.

Thanks for your help.

**Comment by prakhar1989** [comment] 2015-08-05 19:50
I did it when Sindre first tweeted about it - https://github.com/prakhar1989/awesome-courses

**Comment by josephmisiti** [comment] 2015-08-05 19:50
@sindresorhus the badge has been added to `awesome-machine-learning`

**Comment by jbhuang0604** [comment] 2015-08-05 19:54
@sindresorhus the badge has been added to https://github.com/jbhuang0604/awesome-computer-vision

**Comment by AllThingsSmitty** [comment] 2015-08-05 19:57
@dreikanter, @emacs-tw, @mehcode, @ellisonleao, @hzoo, @Calinou, @leereilly, @jondot, @webpro, @alebcay, @unixorn, @stefanbuck, @arslanbilal, @RichardLitt, @cv, @numetriclabz, @shlomi-noach, @dahlia, @mark-rushakoff, @shime, @heyalexej, @brabadu, @hrissimpkins, @therebelrobot, @karlhorky, @matteofigus, @paragonie, @sbilly, @apsdehal, @rshipp, @ashishb, @carpedm20, @paralax, @burningtree, @najela, @matiassingers, @tmcw, @n1trux, @kyleterry, @onurakpolat, @httpsGithubParty, @tiimgreen, @waldyrious, @marmelab, @christian-bromann, @filipelinhares, @itech001, @mmcgrana, @ripienaar, @igorbarinov, @jugoncalves, @diessica, @mmccaff, @maxogden, @caesar0301, @lukasz-madon, @melvin0008, @feross, @matiassingers, @cjbarber, @aleksandar-todorovic, @NARKOZ, @kilimchoi, @Kickball, @jwaterfaucett, @lferov, @Syskaw, @eug:

You're receiving this because you have repos listed in @sindresorhus's Awesome repo. We're trying to apply branding to each repo listed therein. Please see the initial comment on this issue for steps on adding the "Awesome" badge to your repo. Please respond with which repos you've updated with the badge.

Thanks for your help.

**Comment by AllThingsSmitty** [comment] 2015-08-05 20:00
@sindresorhus all owners of repos listed in Awesome have now been notified. So far the response has been quick and positive. It may be a good idea to include something in contributing.md about adding the badge if a repo is approved to be added to the Awesome list.

**Comment by ellisonleao** [comment] 2015-08-05 20:01
@AllThingsSmitty  @sindresorhus  https://github.com/ellisonleao/magictools updated

**Comment by JanVanRyswyck** [comment] 2015-08-05 20:01
@sindresorhus The badge has been added to Awesome Talks: https://github.com/JanVanRyswyck/awesome-talks

**Comment by AllThingsSmitty** [comment] 2015-08-05 20:01
@prakhar1989 thanks! I hadn't seen that I was doing a mass reach-out to everyone at once. 👍🏼

**Comment by christian-bromann** [comment] 2015-08-05 20:05
Added to https://github.com/christian-bromann/awesome-selenium

**Comment by paralax** [comment] 2015-08-05 20:16
awesome-honeypots updated. thanks

- @paralax aka jose nazario

On Wed, Aug 5, 2015 at 3:58 PM, Matt Smith <notifications@github.com> wrote:

> @dreikanter <https://github.com/dreikanter>, @emacs-tw
> <https://github.com/emacs-tw>, @mehcode <https://github.com/mehcode>,
> @ellisonleao <https://github.com/ellisonleao>, @hzoo
> <https://github.com/hzoo>, @Calinou <https://github.com/Calinou>,
> @leereilly <https://github.com/leereilly>, @jondot
> <https://github.com/jondot>, @webpro <https://github.com/webpro>, @alebcay
> <https://github.com/alebcay>, @unixorn <https://github.com/unixorn>,
> @stefanbuck <https://github.com/stefanbuck>, @arslanbilal
> <https://github.com/arslanbilal>, @RichardLitt
> <https://github.com/Richard%20Litt>, @cv <https://github.com/cv>,
> @numetriclabz <https://github.com/numetriclabz>, @shlomi-noach
> <https://github.com/shlomi-noach>, @dahlia <https://github.com/dahlia>,
> @mark-rushakoff <https://github.com/mark-rushakoff>, @shime
> <https://github.com/shime>, @heyalexej <https://github.com/heyalexej>,
> @brabadu <https://github.com/brabadu>, @hrissimpkins, @therebelrobot
> <https://github.com/therebelrobot>, @karlhorky
> <https://github.com/karlhorky>, @matteofigus
> <https://github.com/matteofigus>, @paragonie
> <https://github.com/paragonie>, @sbilly, @apsdehal
> <https://github.com/apsdehal>, @rshipp <https://github.com/rshipp>,
> @ashishb <https://github.com/ashishb>, @carpedm20
> <https://github.com/carpedm20>, @paralax <https://github.com/paralax>,
> @burningtree <https://github.com/burningtree>, @najela
> <https://github.com/najela>, @matiassingers
> <https://github.com/matiassingers>, @tmcw <https://github.com/tmcw>,
> @n1trux <https://github.com/n1trux>, @kyleterry
> <https://github.com/kyleterry>, @onurakpolat
> <https://github.com/onurakpolat>, @httpsGithubParty
> <https://github.com/httpsGithubParty>, @tiimgreen
> <https://github.com/tiimgreen>, @waldyrious
> <https://github.com/waldyrious>, @marmelab <https://github.com/marmelab>,
> @christian-bromann <https://github.com/christian-bromann>, @filipelinhares
> <https://github.com/filipelinhares>, @itech001
> <https://github.com/itech001>, @mmcgrana <https://github.com/mmcgrana>,
> @ripienaar <https://github.com/ripienaar>, @igorbarinov
> <https://github.com/igorbarinov>, @jugoncalves, @diessica, @mmccaff,
> @maxogden, @caesar0301, @lukasz-madon, @melvin0008, @feross,
> @matiassingers <https://github.com/matiassingers>, @cjbarber,
> @aleksandar-todorovic, @NARKOZ, @kilimchoi, @Kickball, @jwaterfauc ett,
> @lferov, @Syskaw, @eug:
>
> You're receiving this because you have repos listed in @sindresorhus's
> Awesome repo. We're trying to apply branding to each repo listed therein.
> Please see the initial comment on this issue for steps on adding the
> "Awesome" badge to your repo. Please respond with which repos you've
> updated with the badge.
>
> Thanks for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/awesome/issues/253#issuecomment-128130674>
> .
>



-- 
jose nazario
For Privacy Act and Paperwork Reduction Act Notice, see page 2

**Comment by unixorn** [comment] 2015-08-05 20:28
Updated [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins).

Thanks!

**Comment by hackerkid** [comment] 2015-08-05 20:35
Added to [Mind Expanding Books](https://github.com/hackerkid/Mind-Expanding-Books) :+1:

**Comment by Calinou** [comment] 2015-08-05 20:56
Added to [Awesome Godot](https://github.com/Calinou/awesome-godot).

**Comment by alebcay** [comment] 2015-08-05 21:13
Added to [Awesome Shell](https://github.com/alebcay/awesome-shell).

**Comment by tiimgreen** [comment] 2015-08-05 21:21
Added to [GitHub Cheat Sheet](https://github.com/tiimgreen/github-cheat-sheet) :+1:

**Comment by filipelinhares** [comment] 2015-08-05 21:48
Added to [Awesome Slack](https://github.com/filipelinhares/awesome-slack) :smile:

**Comment by arslanbilal** [comment] 2015-08-05 21:51
Added to [git cheat sheet](https://github.com/arslanbilal/git-cheat-sheet)

**Comment by stefanbuck** [comment] 2015-08-05 22:05
Added to [Awesome Browser extensions for GitHub](https://github.com/stefanbuck/awesome-browser-extensions-for-github)

**Comment by AllThingsSmitty** [comment] 2015-08-05 22:22
Looks like a few names didn't get highlighted:

@enjalot, @chrissimpkins, @jugoncalves, @diessica, @mmccaff, @maxogden, @caesar0301, @lukasz-madon, @melvin0008, @feross, @cjbarber, @aleksandar-todorovic, @NARKOZ, @kilimchoi, @Kickball, @jwaterfaucett, @alferov, @Syskaw, @eug

**Comment by aleksandar-todorovic** [comment] 2015-08-05 22:28
@AllThingsSmitty That's an expected behavior for those of us who have unsubscribed from this thread.

**Comment by AllThingsSmitty** [comment] 2015-08-05 22:31
@aleksandar-todorovic gotcha. Thanks. Sorry if I was spamming you.

**Comment by alferov** [comment] 2015-08-05 22:31
Thanks, @AllThingsSmitty 

Added to [awesome-gulp](https://github.com/alferov/awesome-gulp)

**Comment by diessica** [comment] 2015-08-05 22:35
Already in [Awesome Sketch](https://github.com/diessica/awesome-sketch). Pretty nice idea, @sindresorhus! :)

**Comment by feross** [comment] 2015-08-05 22:36
added to https://github.com/feross/mad-science-modules

**Comment by matteofigus** [comment] 2015-08-05 22:50
done for https://github.com/matteofigus/awesome-speaking

**Comment by kilimchoi** [comment] 2015-08-05 23:18
Done for https://github.com/kilimchoi/engineering-blogs

**Comment by rshipp** [comment] 2015-08-05 23:20
Done for https://github.com/rshipp/awesome-malware-analysis

**Comment by matiassingers** [comment] 2015-08-05 23:39
- [x] [awesome-readme](https://github.com/matiassingers/awesome-readme)
- [x] [awesome-slack](https://github.com/matiassingers/awesome-slack)

**Comment by sbilly** [comment] 2015-08-05 23:42
Done

https://github.com/sbilly/awesome-security

**Comment by igorbarinov** [comment] 2015-08-05 23:42
- [x] https://github.com/igorbarinov/awesome-bitcoin
- [x] https://github.com/igorbarinov/awesome-data-engineering

**Comment by mmccaff** [comment] 2015-08-06 00:31
Done for https://github.com/mmccaff/PlacesToPostYourStartup

**Comment by chrissimpkins** [comment] 2015-08-06 00:39
Codeface was updated with the badge.  Thanks Sindre.

- [X] https://github.com/chrissimpkins/codeface

**Comment by cjwirth** [comment] 2015-08-06 01:38
:white_check_mark:  https://github.com/cjwirth/awesome-ios-ui/

**Comment by eug** [comment] 2015-08-06 02:00
Done for https://github.com/eug/awesome-opengl

**Comment by Syskaw** [comment] 2015-08-06 02:10
added for 
- [Awesome GIF](https://github.com/Syskaw/awesome-gif)
- [Awesome Open Source Photography](https://github.com/Syskaw/awesome-OpenSourcePhotography)

**Comment by youngwookim** [comment] 2015-08-06 03:00
Done!

https://github.com/youngwookim/awesome-hadoop

**Comment by rshipp** [comment] 2015-08-06 03:00
Added to https://github.com/ahkscript/awesome-AutoHotkey

**Comment by carpedm20** [comment] 2015-08-06 03:22
Same here. https://github.com/carpedm20/awesome-hacking

**Comment by apsdehal** [comment] 2015-08-06 03:55
Added: https://github.com/apsdehal/awesome-ctf

**Comment by shlomi-noach** [comment] 2015-08-06 05:41
Added: https://github.com/shlomi-noach/awesome-mysql

**Comment by avelino** [comment] 2015-08-06 06:17
added on awesome-go https://github.com/avelino/awesome-go

**Comment by brabadu** [comment] 2015-08-06 06:35
added to awesome-fonts https://github.com/brabadu/awesome-fonts

**Comment by zhaopuming** [comment] 2015-08-06 06:39
added to awesome-d https://github.com/zhaopuming/awesome-d

**Comment by owainlewis** [comment] 2015-08-06 07:43
added to awesome artificial intelligence https://github.com/owainlewis/awesome-artificial-intelligence

**Comment by onurakpolat** [comment] 2015-08-06 08:04
Joining the spammers club 😈 - added to awesome-bigdata
<https://github.com/onurakpolat/awesome-bigdata>

--

onurakpolat.com <http://www.onurakpolat.com/> | onur.akpolat@gmail.com | +49
151 280 21915 <%2B4915128021915> | @OnurAkpolat

**Comment by karlhorky** [comment] 2015-08-06 08:20
Added to [Learn to Program](https://github.com/karlhorky/learn-to-program)

**Comment by shime** [comment] 2015-08-06 08:56
added to [shime/creative-commons-media](https://github.com/shime/creative-commons-media)

**Comment by ekremkaraca** [comment] 2015-08-06 09:19
Mission completed für [awesome-rails](https://github.com/ekremkaraca/awesome-rails)

**Comment by lukasz-madon** [comment] 2015-08-06 09:42
Added for https://github.com/lukasz-madon/awesome-remote-job

**Comment by melvin0008** [comment] 2015-08-06 11:02
Added to [https://github.com/melvin0008/awesome-projects-boilerplates](https://github.com/melvin0008/awesome-projects-boilerplates)

**Comment by Fr0sT-Brutal** [comment] 2015-08-06 12:18
See little sense in this but added to https://github.com/Fr0sT-Brutal/awesome-delphi

**Comment by chiraggude** [comment] 2015-08-06 13:14
Added to https://github.com/chiraggude/awesome-laravel

**Comment by diegocard** [comment] 2015-08-06 20:52
Done on [Awesome HTML5](https://github.com/diegocard/awesome-html5)

**Comment by busterc** [comment] 2015-08-06 21:36
Added to [Cordova](https://github.com/busterc/awesome-cordova)

**Comment by markets** [comment] 2015-08-07 14:40
Added to [![Awesome](https://raw.githubusercontent.com/markets/awesome-ruby/gh-pages/images/logo.png)](https://github.com/markets/awesome-ruby) 

:+1: :+1:

**Comment by uzulla** [comment] 2015-08-07 14:52
Added to https://github.com/hachiojipm/awesome-perl
:+1: nice badge.

**Comment by owainlewis** [comment] 2015-08-07 15:52
Awesome

![](http://media.giphy.com/media/MCKQEmHkUyGf6/giphy.gif)

**Comment by CraigyDavi** [comment] 2015-08-07 15:59
I'm working my way down the list and referencing the PRs to this issue with the name of `Add awesome list badge`!
Ones I have missed out:
- https://github.com/maciejczyzewski/retter (don't know where to put the badge)

**Comment by CraigyDavi** [comment] 2015-08-07 17:47
Done! All awesome lists should have a pull-request adding the badge. :smile:

**Comment by maciejczyzewski** [comment] 2015-08-07 19:22
@CraigyDavi https://github.com/maciejczyzewski/retter ready to proudly shine... :smile:

**Comment by CraigyDavi** [comment] 2015-08-07 19:27
> @CraigyDavi https://github.com/maciejczyzewski/retter ready to proudly shine...

:sunglasses: :+1:

**Comment by waldyrious** [comment] 2015-08-07 20:15
@CraigyDavi appropriately enough, that was an awesome job! [Awesome-open-companies](https://github.com/waldyrious/awesome-open-companies) has just jumped aboard :)

**Comment by benoitjadinon** [comment] 2015-08-07 20:49
https://github.com/benoitjadinon/awesome-xamarin is badged. over and out.

**Comment by jwaterfaucett** [comment] 2015-08-08 13:42
https://github.com/jwaterfaucett/awesome-foss-apps is badeged thanks @CraigyDavi :)

**Comment by dreikanter** [comment] 2015-08-08 14:01
Done for https://github.com/dreikanter/sublime-bookmarks and https://github.com/dreikanter/ruby-bookmarks

**Comment by fzaninotto** [comment] 2015-08-10 08:58
Done on [Awesome REST](https://github.com/marmelab/awesome-rest)

**Comment by lauris** [comment] 2015-08-11 18:59
Merged on [Awesome Scala](https://github.com/lauris/awesome-scala) (y)

**Comment by ashishb** [comment] 2015-08-12 01:44
Added to android-security-awesome.

**Comment by marcobiedermann** [comment] 2015-08-24 14:24
@AllThingsSmitty Added to [Search Engine Optimization (SEO)](https://github.com/marcobiedermann/search-engine-optimization) :+1:

**Comment by itech001** [comment] 2015-08-28 04:57
added for https://github.com/ciandcd/awesome-ciandcd

**Comment by AllThingsSmitty** [comment] 2016-02-27 02:24
At some point we should spot check the Awesome list to make certain we haven't missed any projects that need the badge.

**Comment by SrinivasanTarget** [comment] 2016-07-28 14:32
@sindresorhus Added to https://github.com/SrinivasanTarget/awesome-appium

**Closed** 2016-10-26 09:05 UTC
Labels: help wanted
