### ISSUE TITLE
Hi, Django Link is broken

### ISSUE THREAD

**Issue by iaboots** [sindresorhus/awesome#1481] opened 2018-12-20 00:50 UTC
Hi, Django Link is broken

**Comment by mashed-potatoes** [comment] 2018-12-23 13:36
[duplicate](https://github.com/sindresorhus/awesome/issues/1478)

**Comment by mjhea0** [comment] 2018-12-29 15:41
https://github.com/sindresorhus/awesome/pull/1484

**Comment by sindresorhus** [comment] 2018-12-29 15:55
Duplicate of #1478

**Closed by sindresorhus** 2018-12-29 15:55 UTC
