### ISSUE TITLE
What about Alphabetization?

### ISSUE THREAD

**Issue by switchhax** [sindresorhus/awesome#304] opened 2015-09-05 11:44 UTC
I´ve seen that at many other projects and i ask many other project maintainers, if they would do it. It helps at points like search-ability, clarity and structure. What do you think? I could do that
I mean only the chapters should be alphabetized, the table of contents should not. Or do the follow a special order?

**Comment by sindresorhus** [comment] 2015-09-05 12:27
Duplicate of #216.

**Closed by sindresorhus** 2015-09-05 12:27 UTC
