### ISSUE TITLE
Alphabatize

### ISSUE THREAD

**Issue by Mrashes** [sindresorhus/awesome#1109] opened 2017-10-25 19:17 UTC
Hey all,

I was looking through the readme and find it kind of sprawling.  Could I contribute by alphabetizing the list to make it easier to read?

-Max

**Comment by sindresorhus** [comment] 2017-10-26 08:06
Duplicate of https://github.com/sindresorhus/awesome/pull/417

**Closed by sindresorhus** 2017-10-26 08:06 UTC
