### ISSUE TITLE
Non-english lists

### ISSUE THREAD

**Issue by davisonio** [sindresorhus/awesome#479] opened 2016-01-15 19:36 UTC
How about adding lists for awesome lists which aren't in english?

We could create files called `readme-de.md` `readme-fr.md` etc. For example there's lots of awesome lists in Chinese from [here](https://github.com/justjavac/awesome-awesomeness-zh_CN).

Obviously this may take some work ensuring that lists are suitable and follow the awesome manifesto, so we'd need some help from those who are able to understand those languages and check for a license, contributing guidelines etc.

**Comment by aleksandar-todorovic** [comment] 2016-01-16 13:39
Duplicate of #153

**Comment by davisonio** [comment] 2016-01-16 14:04
@aleksandar-todorovic Is it really? I thought #153 was about adding a category for lists about *places & countries*. e.g. https://github.com/rubysg/singapore or https://github.com/rubysg/singapore.

I'm talking about adding a completely new list of lists in this repository which are in a *different language*.

For example in the list we currently have a link to https://github.com/arslanbilal/git-cheat-sheet ... but we don't have a link to https://github.com/arslanbilal/git-cheat-sheet/blob/master/other-sheets/git-cheat-sheet-es.md. We could add a `readme-es.md` with a link to this resource instead.

**Comment by aleksandar-todorovic** [comment] 2016-01-16 14:23
Well think of it this way: what's the point of creating Spanish list of awesome lists if the content that gets linked in those lists is going to be in English? I don't see how anyone would benefit from such lists (those who understand English would just look here, those who don't will stumble upon some English resource and won't understand a thing). 

Therefore, the lists need to be localized and link to the content available in that language. While I don't think that separating lists by country or region is really the best way to do that (in fact, I agree with you, they should be sepa

**Comment by aleksandar-todorovic** [comment] 2016-01-16 14:24
Well think of it this way: what's the point of creating Spanish list of awesome lists if the content that gets linked in those lists is going to be in English? I don't see how anyone would benefit from such lists (those who understand English would just look here, those who don't will stumble upon some English resource and won't understand a thing). 

Therefore, the lists need to be localized and link to the content available in that language. While I don't think that separating lists by country or region is really the best way to do that (in fact, I agree with you, they should be separated by languages), I'd say that the issue 153 is still open for discussion.

**Comment by aleksandar-todorovic** [comment] 2016-01-16 14:26
Sorry for the double comment, shitty 3G Internet.

**Comment by davisonio** [comment] 2016-01-16 14:34
Yes, you're right there are quite a few which are like that but there's also lists like [this one](https://github.com/vhf/free-programming-books/blob/master/free-programming-books-zh.md) which is is Chinese and only links to content in Chinese.

Yes that's also a good point, this was just an idea and I'm okay with moving my comment to #153 as the issues are quite similar.

**Comment by aleksandar-todorovic** [comment] 2016-01-16 14:38
All right then, I'm glad we agreed.

**Closed by aleksandar-todorovic** 2016-01-16 14:38 UTC
