### ISSUE TITLE
[RFC] - Introducing mmarkdown

### ISSUE THREAD

**Issue by albinotonnina** [sindresorhus/awesome#1287] opened 2018-05-01 04:31 UTC
I made this little javascript tool recently:

https://github.com/albinotonnina/mmarkdown

What it does is so simple that I will just paste here the description of the project:

mmarkdown:
Interpret mmd fenced code blocks in a markdown file and generate a cooler version of it.
It could be useful for big projects like this one, that rely almost entirely on markdown files as an output.

An example in the wild:
https://github.com/albinotonnina/css-in-js/tree/mmarkdown

Using mmarkdown (and node.js) I made a little app to fetch and process data from npm and github (given a json list of package/repositories) and generate an updated markdown file.

You could add some sort of automation to update the markdown file programmatically.

It could be interesting or not. I thought it was worth showing it to you. 😀

IN THIS PARTICULAR PROJECT, you could make a simple webapp to manage submissions, with sorting and filtering and voting that would output data that mmarkdown would use to generate the awesome readme file.

You could add statistics to the linked resources or augment the data somehow.

What you think about this? 
I would like to start a discussion.

**Comment by sindresorhus** [comment] 2018-05-01 04:35
Duplicate of #1283

**Comment by sindresorhus** [comment] 2018-05-01 04:35
No need to open a new issue. Please continue the discussion in #1283.

**Closed by sindresorhus** 2018-05-01 04:35 UTC
